services:
  mysql:
    image: mysql:8.0
    container_name: projeto_exemplo_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: labinfo
      MYSQL_DATABASE: aplicacao
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./banco_de_dados/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  mysql_data:
